name: Build on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'  # Enable caching for Yarn dependencies

      - name: Install Dependencies
        run: yarn install

      - name: Generate prisa client
        run: yarn db:generate
        
      - name: Run Build
        run: yarn build
