name: Build Succeeds on PR

on:
  pull_request:
    branches:
      - master
      - main
jobs:
  builds:
    name: Build the Project
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@versionv3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: Install Dependencies
          run: yarn install

        - name: 
        - name: Run Build
          run: yarn build